# Generated by Django 4.2.16 on 2024-09-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='points',
            new_name='direct_points',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='indirect_points',
            field=models.IntegerField(default=0),
        ),
    ]
