# Generated by Django 4.2.16 on 2024-09-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_rename_points_affiliate_direct_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='withdrawed_points',
            field=models.IntegerField(default=0),
        ),
    ]
