# Generated by Django 4.2.16 on 2024-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('XAF', 'XAF')], default='XAF', max_length=7),
        ),
    ]
