# Generated by Django 4.2.16 on 2024-09-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0002_publications_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
