# Generated by Django 4.2.16 on 2024-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='affiliate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_affiliation',
            field=models.BooleanField(default=False),
        ),
    ]
